apiVersion: v1
kind: Service
metadata:
  name: pg
spec:
  ports:
  - port: 5432
---
apiVersion: v1
kind: Endpoints
metadata:
  name: pg
subsets:
- addresses:
  - ip: 34.193.153.222
  ports:
  - port: 5432
