#!/bin/bash

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

# Bootstrap kubectl configuration
source secrets/kube/kubectl.env
export PATH=${PATH}:$(pwd)/bin

kubectl apply --recursive=true --filename=manifests/
