#!/bin/bash

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/../secrets"

read -p "Enter the vault password: " VAULT_PASSWORD

tar cvf vault.tar kube/

travis encrypt VAULT_PASSWORD=${VAULT_PASSWORD} --add

echo ${VAULT_PASSWORD} | gpg \
  --passphrase-fd 0 \
  --batch --no-tty --yes \
  --output vault.tar.gpg \
  --symmetric vault.tar
