#!/bin/bash

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

mkdir -p bin/

if [ ! -f bin/kubectl ]; then
  echo "installing kubectl"
  curl https://storage.googleapis.com/kubernetes-release/release/v1.4.6/kubernetes-client-linux-amd64.tar.gz \
    -o bin/kubectl.tar.gz
  pushd bin/
  tar xf kubectl.tar.gz
  mv kubernetes/client/bin/kubectl ./kubectl
  rm -r kubernetes kubectl.tar.gz
  chmod +x ./kubectl
  popd
fi

if [ ! -f secrets/kube/kubectl.env ]; then
  echo "extracting kubectl connection secrets"

  if [ -z "${VAULT_PASSWORD:-}" ]; then
    echo "VAULT_PASSWORD is unset." >/dev/stderr
    exit 1
  fi

  script/unlock
fi
