#!/bin/bash

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/../secrets"

if [ -z "${VAULT_PASSWORD:-}" ]; then
  read -p "Enter the vault password: " VAULT_PASSWORD
fi

echo ${VAULT_PASSWORD} | gpg \
  --passphrase-fd 0 \
  --batch --no-tty --yes \
  --output vault.tar \
  vault.tar.gpg

tar xf vault.tar
