name: shipit

on:
  push:
    branches:
      - master

jobs:
  shipit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v1.2.0
      with:
        python-version: 3.6
    - name: test
      run: script/ci/test
    - name: deploy
      run: script/ci/deploy
